# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\x12\x06triton\x1a\x1bgoogle/protobuf/empty.proto\"T\n\x06Tensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x1f\n\x05\x64type\x18\x03 \x01(\x0e\x32\x10.triton.DataType\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"\'\n\x05\x42\x61tch\x12\x1e\n\x06tensor\x18\x01 \x03(\x0b\x32\x0e.triton.Tensor\"O\n\x0cInferRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\r\x12\x1d\n\x06inputs\x18\x03 \x03(\x0b\x32\r.triton.Batch\"r\n\rInferResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\r\x12\x12\n\nerror_code\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\x1e\n\x07outputs\x18\x05 \x03(\x0b\x32\r.triton.Batch\"\x81\x01\n\x0bModelStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x1e\n\x06inputs\x18\x03 \x03(\x0b\x32\x0e.triton.Tensor\x12\x1f\n\x07outputs\x18\x04 \x03(\x0b\x32\x0e.triton.Tensor\x12\x0f\n\x07running\x18\x05 \x01(\x05\"0\n\nModelRepos\x12\"\n\x05model\x18\x01 \x03(\x0b\x32\x13.triton.ModelStatus\"\x1b\n\x0bLoadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t*B\n\x08\x44\x61taType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x42YTE\x10\x01\x12\t\n\x05\x42YTE2\x10\x02\x12\t\n\x05\x42YTE4\x10\x04\x12\t\n\x05\x42YTE8\x10\x08\x32\x44\n\nModelInfer\x12\x36\n\x05Infer\x12\x14.triton.InferRequest\x1a\x15.triton.InferResponse\"\x00\x32\xc9\x01\n\x07Greeter\x12\x42\n\x12GetModelRepository\x12\x16.google.protobuf.Empty\x1a\x12.triton.ModelRepos\"\x00\x12<\n\x0bUploadModel\x12\x13.triton.LoadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\x0bRemoveModel\x12\x13.triton.LoadRequest\x1a\x16.google.protobuf.Empty\"\x00\x42,\n\x16io.grpc.examples.inferB\nInferProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026io.grpc.examples.inferB\nInferProtoP\001\242\002\003HLW'
  _DATATYPE._serialized_start=587
  _DATATYPE._serialized_end=653
  _TENSOR._serialized_start=52
  _TENSOR._serialized_end=136
  _BATCH._serialized_start=138
  _BATCH._serialized_end=177
  _INFERREQUEST._serialized_start=179
  _INFERREQUEST._serialized_end=258
  _INFERRESPONSE._serialized_start=260
  _INFERRESPONSE._serialized_end=374
  _MODELSTATUS._serialized_start=377
  _MODELSTATUS._serialized_end=506
  _MODELREPOS._serialized_start=508
  _MODELREPOS._serialized_end=556
  _LOADREQUEST._serialized_start=558
  _LOADREQUEST._serialized_end=585
  _MODELINFER._serialized_start=655
  _MODELINFER._serialized_end=723
  _GREETER._serialized_start=726
  _GREETER._serialized_end=927
# @@protoc_insertion_point(module_scope)
